[package]
name = "timesync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["clock"] }
libc = "0.2.176"
nix = "0.30.1"
